name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew dependencyUpdates -Drevision=release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true